/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef OONE10GEVPDF
#define OONE10GEVPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class OOne10GeVPdf : public RooAbsPdf {
public:
  OOne10GeVPdf() {} ; 
  ///OOne10GeVPdf( RooRealVar xRV, RooRealVar cofRV; OOne10GeVPdf) {} ; 
  OOne10GeVPdf(const char *name, const char *title,
	      ///RooAbsReal& _x,
	      RooAbsReal& _cof);
  OOne10GeVPdf(const OOne10GeVPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new OOne10GeVPdf(*this,newname); }
  inline virtual ~OOne10GeVPdf() { }

protected:

  ///RooRealProxy x ;
  RooRealProxy cof ;
  
  Double_t evaluate() const ;

private:

  ClassDef(OOne10GeVPdf,1) // Your description goes here...

};
 
#endif
