/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BKGLINEARPDF
#define BKGLINEARPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class BkgLinearPdf : public RooAbsPdf {
public:
  BkgLinearPdf() {} ; 
  BkgLinearPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  BkgLinearPdf(const BkgLinearPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new BkgLinearPdf(*this,newname); }
  inline virtual ~BkgLinearPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;

private:

  ClassDef(BkgLinearPdf,1) // Your description goes here...
};
 
#endif
